# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18f129259f3d43d8237c5790fd538cb570c44452b3265c19d0e420edc18bd82d471682d977c30334fe5026ca7cbacd66a34e6c303c68d09e79720a60cf989cea

test:
  secret_key_base: 1b3a414a05ee9f156a7d28c0fd52e590dd264aa1be87bd5252ccac786aca68f37c538a7c6902dbe6216b113518dca644d17c544f0ca60ba3f2977f0a692ca481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
